//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beertown.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConnectingPassage
    {
        public int ConnectingPassageId { get; set; }
        public int Station1Id { get; set; }
        public int Station2Id { get; set; }
        public decimal DurationMins { get; set; }
    
        public virtual Station StationIn { get; set; }
        public virtual Station StationOut { get; set; }
    }
}
