//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beertown.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class LineTarif
    {
        public int LineTarifId { get; set; }
        public int LineId { get; set; }
        public System.DateTime ActualDate { get; set; }
        public System.DateTime ActualEndDate { get; set; }
        public decimal Cost { get; set; }
    
        public virtual Line Line { get; set; }
    }
}
