//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beertown.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SubwayDatabaseEntities : DbContext
    {
        public SubwayDatabaseEntities()
            : base("name=SubwayDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ConnectingPassage> ConnectingPassages { get; set; }
        public virtual DbSet<Haul> Hauls { get; set; }
        public virtual DbSet<Line> Lines { get; set; }
        public virtual DbSet<Station> Stations { get; set; }
        public virtual DbSet<LineTarif> LineTarifs { get; set; }
    }
}
